// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto2.proto

package armmotorhelp;

public final class Proto2 {
  private Proto2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArmStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:armmotorhelp.ArmState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string worker_id = 1;</code>
     */
    java.lang.String getWorkerId();
    /**
     * <code>string worker_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getWorkerIdBytes();

    /**
     * <code>float motor_load = 2;</code>
     */
    float getMotorLoad();
  }
  /**
   * Protobuf type {@code armmotorhelp.ArmState}
   */
  public  static final class ArmState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:armmotorhelp.ArmState)
      ArmStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArmState.newBuilder() to construct.
    private ArmState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArmState() {
      workerId_ = "";
      motorLoad_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ArmState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              workerId_ = s;
              break;
            }
            case 21: {

              motorLoad_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return armmotorhelp.Proto2.internal_static_armmotorhelp_ArmState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return armmotorhelp.Proto2.internal_static_armmotorhelp_ArmState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              armmotorhelp.Proto2.ArmState.class, armmotorhelp.Proto2.ArmState.Builder.class);
    }

    public static final int WORKER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object workerId_;
    /**
     * <code>string worker_id = 1;</code>
     */
    public java.lang.String getWorkerId() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workerId_ = s;
        return s;
      }
    }
    /**
     * <code>string worker_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkerIdBytes() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOTOR_LOAD_FIELD_NUMBER = 2;
    private float motorLoad_;
    /**
     * <code>float motor_load = 2;</code>
     */
    public float getMotorLoad() {
      return motorLoad_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWorkerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workerId_);
      }
      if (motorLoad_ != 0F) {
        output.writeFloat(2, motorLoad_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWorkerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workerId_);
      }
      if (motorLoad_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, motorLoad_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof armmotorhelp.Proto2.ArmState)) {
        return super.equals(obj);
      }
      armmotorhelp.Proto2.ArmState other = (armmotorhelp.Proto2.ArmState) obj;

      boolean result = true;
      result = result && getWorkerId()
          .equals(other.getWorkerId());
      result = result && (
          java.lang.Float.floatToIntBits(getMotorLoad())
          == java.lang.Float.floatToIntBits(
              other.getMotorLoad()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORKER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerId().hashCode();
      hash = (37 * hash) + MOTOR_LOAD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMotorLoad());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static armmotorhelp.Proto2.ArmState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.ArmState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.ArmState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.ArmState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.ArmState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.ArmState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.ArmState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.ArmState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static armmotorhelp.Proto2.ArmState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.ArmState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static armmotorhelp.Proto2.ArmState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.ArmState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(armmotorhelp.Proto2.ArmState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code armmotorhelp.ArmState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:armmotorhelp.ArmState)
        armmotorhelp.Proto2.ArmStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_ArmState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_ArmState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                armmotorhelp.Proto2.ArmState.class, armmotorhelp.Proto2.ArmState.Builder.class);
      }

      // Construct using armmotorhelp.Proto2.ArmState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        workerId_ = "";

        motorLoad_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_ArmState_descriptor;
      }

      @java.lang.Override
      public armmotorhelp.Proto2.ArmState getDefaultInstanceForType() {
        return armmotorhelp.Proto2.ArmState.getDefaultInstance();
      }

      @java.lang.Override
      public armmotorhelp.Proto2.ArmState build() {
        armmotorhelp.Proto2.ArmState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public armmotorhelp.Proto2.ArmState buildPartial() {
        armmotorhelp.Proto2.ArmState result = new armmotorhelp.Proto2.ArmState(this);
        result.workerId_ = workerId_;
        result.motorLoad_ = motorLoad_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof armmotorhelp.Proto2.ArmState) {
          return mergeFrom((armmotorhelp.Proto2.ArmState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(armmotorhelp.Proto2.ArmState other) {
        if (other == armmotorhelp.Proto2.ArmState.getDefaultInstance()) return this;
        if (!other.getWorkerId().isEmpty()) {
          workerId_ = other.workerId_;
          onChanged();
        }
        if (other.getMotorLoad() != 0F) {
          setMotorLoad(other.getMotorLoad());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        armmotorhelp.Proto2.ArmState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (armmotorhelp.Proto2.ArmState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object workerId_ = "";
      /**
       * <code>string worker_id = 1;</code>
       */
      public java.lang.String getWorkerId() {
        java.lang.Object ref = workerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWorkerIdBytes() {
        java.lang.Object ref = workerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder setWorkerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder clearWorkerId() {
        
        workerId_ = getDefaultInstance().getWorkerId();
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder setWorkerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workerId_ = value;
        onChanged();
        return this;
      }

      private float motorLoad_ ;
      /**
       * <code>float motor_load = 2;</code>
       */
      public float getMotorLoad() {
        return motorLoad_;
      }
      /**
       * <code>float motor_load = 2;</code>
       */
      public Builder setMotorLoad(float value) {
        
        motorLoad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float motor_load = 2;</code>
       */
      public Builder clearMotorLoad() {
        
        motorLoad_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:armmotorhelp.ArmState)
    }

    // @@protoc_insertion_point(class_scope:armmotorhelp.ArmState)
    private static final armmotorhelp.Proto2.ArmState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new armmotorhelp.Proto2.ArmState();
    }

    public static armmotorhelp.Proto2.ArmState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArmState>
        PARSER = new com.google.protobuf.AbstractParser<ArmState>() {
      @java.lang.Override
      public ArmState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArmState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ArmState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ArmState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public armmotorhelp.Proto2.ArmState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ArmSessionSummaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:armmotorhelp.ArmSessionSummary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string session_summary = 1;</code>
     */
    java.lang.String getSessionSummary();
    /**
     * <code>string session_summary = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionSummaryBytes();

    /**
     * <code>int32 total_events = 2;</code>
     */
    int getTotalEvents();
  }
  /**
   * Protobuf type {@code armmotorhelp.ArmSessionSummary}
   */
  public  static final class ArmSessionSummary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:armmotorhelp.ArmSessionSummary)
      ArmSessionSummaryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArmSessionSummary.newBuilder() to construct.
    private ArmSessionSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArmSessionSummary() {
      sessionSummary_ = "";
      totalEvents_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ArmSessionSummary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionSummary_ = s;
              break;
            }
            case 16: {

              totalEvents_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return armmotorhelp.Proto2.internal_static_armmotorhelp_ArmSessionSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return armmotorhelp.Proto2.internal_static_armmotorhelp_ArmSessionSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              armmotorhelp.Proto2.ArmSessionSummary.class, armmotorhelp.Proto2.ArmSessionSummary.Builder.class);
    }

    public static final int SESSION_SUMMARY_FIELD_NUMBER = 1;
    private volatile java.lang.Object sessionSummary_;
    /**
     * <code>string session_summary = 1;</code>
     */
    public java.lang.String getSessionSummary() {
      java.lang.Object ref = sessionSummary_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionSummary_ = s;
        return s;
      }
    }
    /**
     * <code>string session_summary = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionSummaryBytes() {
      java.lang.Object ref = sessionSummary_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionSummary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTAL_EVENTS_FIELD_NUMBER = 2;
    private int totalEvents_;
    /**
     * <code>int32 total_events = 2;</code>
     */
    public int getTotalEvents() {
      return totalEvents_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSessionSummaryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionSummary_);
      }
      if (totalEvents_ != 0) {
        output.writeInt32(2, totalEvents_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSessionSummaryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionSummary_);
      }
      if (totalEvents_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalEvents_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof armmotorhelp.Proto2.ArmSessionSummary)) {
        return super.equals(obj);
      }
      armmotorhelp.Proto2.ArmSessionSummary other = (armmotorhelp.Proto2.ArmSessionSummary) obj;

      boolean result = true;
      result = result && getSessionSummary()
          .equals(other.getSessionSummary());
      result = result && (getTotalEvents()
          == other.getTotalEvents());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSION_SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getSessionSummary().hashCode();
      hash = (37 * hash) + TOTAL_EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getTotalEvents();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static armmotorhelp.Proto2.ArmSessionSummary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.ArmSessionSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(armmotorhelp.Proto2.ArmSessionSummary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code armmotorhelp.ArmSessionSummary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:armmotorhelp.ArmSessionSummary)
        armmotorhelp.Proto2.ArmSessionSummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_ArmSessionSummary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_ArmSessionSummary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                armmotorhelp.Proto2.ArmSessionSummary.class, armmotorhelp.Proto2.ArmSessionSummary.Builder.class);
      }

      // Construct using armmotorhelp.Proto2.ArmSessionSummary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionSummary_ = "";

        totalEvents_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_ArmSessionSummary_descriptor;
      }

      @java.lang.Override
      public armmotorhelp.Proto2.ArmSessionSummary getDefaultInstanceForType() {
        return armmotorhelp.Proto2.ArmSessionSummary.getDefaultInstance();
      }

      @java.lang.Override
      public armmotorhelp.Proto2.ArmSessionSummary build() {
        armmotorhelp.Proto2.ArmSessionSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public armmotorhelp.Proto2.ArmSessionSummary buildPartial() {
        armmotorhelp.Proto2.ArmSessionSummary result = new armmotorhelp.Proto2.ArmSessionSummary(this);
        result.sessionSummary_ = sessionSummary_;
        result.totalEvents_ = totalEvents_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof armmotorhelp.Proto2.ArmSessionSummary) {
          return mergeFrom((armmotorhelp.Proto2.ArmSessionSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(armmotorhelp.Proto2.ArmSessionSummary other) {
        if (other == armmotorhelp.Proto2.ArmSessionSummary.getDefaultInstance()) return this;
        if (!other.getSessionSummary().isEmpty()) {
          sessionSummary_ = other.sessionSummary_;
          onChanged();
        }
        if (other.getTotalEvents() != 0) {
          setTotalEvents(other.getTotalEvents());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        armmotorhelp.Proto2.ArmSessionSummary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (armmotorhelp.Proto2.ArmSessionSummary) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sessionSummary_ = "";
      /**
       * <code>string session_summary = 1;</code>
       */
      public java.lang.String getSessionSummary() {
        java.lang.Object ref = sessionSummary_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionSummary_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string session_summary = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionSummaryBytes() {
        java.lang.Object ref = sessionSummary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionSummary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string session_summary = 1;</code>
       */
      public Builder setSessionSummary(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionSummary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string session_summary = 1;</code>
       */
      public Builder clearSessionSummary() {
        
        sessionSummary_ = getDefaultInstance().getSessionSummary();
        onChanged();
        return this;
      }
      /**
       * <code>string session_summary = 1;</code>
       */
      public Builder setSessionSummaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionSummary_ = value;
        onChanged();
        return this;
      }

      private int totalEvents_ ;
      /**
       * <code>int32 total_events = 2;</code>
       */
      public int getTotalEvents() {
        return totalEvents_;
      }
      /**
       * <code>int32 total_events = 2;</code>
       */
      public Builder setTotalEvents(int value) {
        
        totalEvents_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 total_events = 2;</code>
       */
      public Builder clearTotalEvents() {
        
        totalEvents_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:armmotorhelp.ArmSessionSummary)
    }

    // @@protoc_insertion_point(class_scope:armmotorhelp.ArmSessionSummary)
    private static final armmotorhelp.Proto2.ArmSessionSummary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new armmotorhelp.Proto2.ArmSessionSummary();
    }

    public static armmotorhelp.Proto2.ArmSessionSummary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArmSessionSummary>
        PARSER = new com.google.protobuf.AbstractParser<ArmSessionSummary>() {
      @java.lang.Override
      public ArmSessionSummary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArmSessionSummary(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ArmSessionSummary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ArmSessionSummary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public armmotorhelp.Proto2.ArmSessionSummary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmergencyStopRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:armmotorhelp.EmergencyStopRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string worker_id = 1;</code>
     */
    java.lang.String getWorkerId();
    /**
     * <code>string worker_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getWorkerIdBytes();

    /**
     * <code>string location = 3;</code>
     */
    java.lang.String getLocation();
    /**
     * <code>string location = 3;</code>
     */
    com.google.protobuf.ByteString
        getLocationBytes();
  }
  /**
   * Protobuf type {@code armmotorhelp.EmergencyStopRequest}
   */
  public  static final class EmergencyStopRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:armmotorhelp.EmergencyStopRequest)
      EmergencyStopRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmergencyStopRequest.newBuilder() to construct.
    private EmergencyStopRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmergencyStopRequest() {
      workerId_ = "";
      location_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmergencyStopRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              workerId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              location_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return armmotorhelp.Proto2.internal_static_armmotorhelp_EmergencyStopRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return armmotorhelp.Proto2.internal_static_armmotorhelp_EmergencyStopRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              armmotorhelp.Proto2.EmergencyStopRequest.class, armmotorhelp.Proto2.EmergencyStopRequest.Builder.class);
    }

    public static final int WORKER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object workerId_;
    /**
     * <code>string worker_id = 1;</code>
     */
    public java.lang.String getWorkerId() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workerId_ = s;
        return s;
      }
    }
    /**
     * <code>string worker_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkerIdBytes() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object location_;
    /**
     * <code>string location = 3;</code>
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <code>string location = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWorkerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workerId_);
      }
      if (!getLocationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, location_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWorkerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workerId_);
      }
      if (!getLocationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, location_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof armmotorhelp.Proto2.EmergencyStopRequest)) {
        return super.equals(obj);
      }
      armmotorhelp.Proto2.EmergencyStopRequest other = (armmotorhelp.Proto2.EmergencyStopRequest) obj;

      boolean result = true;
      result = result && getWorkerId()
          .equals(other.getWorkerId());
      result = result && getLocation()
          .equals(other.getLocation());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORKER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerId().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static armmotorhelp.Proto2.EmergencyStopRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.EmergencyStopRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(armmotorhelp.Proto2.EmergencyStopRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code armmotorhelp.EmergencyStopRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:armmotorhelp.EmergencyStopRequest)
        armmotorhelp.Proto2.EmergencyStopRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_EmergencyStopRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_EmergencyStopRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                armmotorhelp.Proto2.EmergencyStopRequest.class, armmotorhelp.Proto2.EmergencyStopRequest.Builder.class);
      }

      // Construct using armmotorhelp.Proto2.EmergencyStopRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        workerId_ = "";

        location_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_EmergencyStopRequest_descriptor;
      }

      @java.lang.Override
      public armmotorhelp.Proto2.EmergencyStopRequest getDefaultInstanceForType() {
        return armmotorhelp.Proto2.EmergencyStopRequest.getDefaultInstance();
      }

      @java.lang.Override
      public armmotorhelp.Proto2.EmergencyStopRequest build() {
        armmotorhelp.Proto2.EmergencyStopRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public armmotorhelp.Proto2.EmergencyStopRequest buildPartial() {
        armmotorhelp.Proto2.EmergencyStopRequest result = new armmotorhelp.Proto2.EmergencyStopRequest(this);
        result.workerId_ = workerId_;
        result.location_ = location_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof armmotorhelp.Proto2.EmergencyStopRequest) {
          return mergeFrom((armmotorhelp.Proto2.EmergencyStopRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(armmotorhelp.Proto2.EmergencyStopRequest other) {
        if (other == armmotorhelp.Proto2.EmergencyStopRequest.getDefaultInstance()) return this;
        if (!other.getWorkerId().isEmpty()) {
          workerId_ = other.workerId_;
          onChanged();
        }
        if (!other.getLocation().isEmpty()) {
          location_ = other.location_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        armmotorhelp.Proto2.EmergencyStopRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (armmotorhelp.Proto2.EmergencyStopRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object workerId_ = "";
      /**
       * <code>string worker_id = 1;</code>
       */
      public java.lang.String getWorkerId() {
        java.lang.Object ref = workerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWorkerIdBytes() {
        java.lang.Object ref = workerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder setWorkerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder clearWorkerId() {
        
        workerId_ = getDefaultInstance().getWorkerId();
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder setWorkerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workerId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <code>string location = 3;</code>
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string location = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string location = 3;</code>
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string location = 3;</code>
       */
      public Builder clearLocation() {
        
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      /**
       * <code>string location = 3;</code>
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        location_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:armmotorhelp.EmergencyStopRequest)
    }

    // @@protoc_insertion_point(class_scope:armmotorhelp.EmergencyStopRequest)
    private static final armmotorhelp.Proto2.EmergencyStopRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new armmotorhelp.Proto2.EmergencyStopRequest();
    }

    public static armmotorhelp.Proto2.EmergencyStopRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmergencyStopRequest>
        PARSER = new com.google.protobuf.AbstractParser<EmergencyStopRequest>() {
      @java.lang.Override
      public EmergencyStopRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmergencyStopRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmergencyStopRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmergencyStopRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public armmotorhelp.Proto2.EmergencyStopRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmergencyStopAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:armmotorhelp.EmergencyStopAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool motors_stopped = 1;</code>
     */
    boolean getMotorsStopped();

    /**
     * <code>string instructions = 2;</code>
     */
    java.lang.String getInstructions();
    /**
     * <code>string instructions = 2;</code>
     */
    com.google.protobuf.ByteString
        getInstructionsBytes();
  }
  /**
   * Protobuf type {@code armmotorhelp.EmergencyStopAck}
   */
  public  static final class EmergencyStopAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:armmotorhelp.EmergencyStopAck)
      EmergencyStopAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmergencyStopAck.newBuilder() to construct.
    private EmergencyStopAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmergencyStopAck() {
      motorsStopped_ = false;
      instructions_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmergencyStopAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              motorsStopped_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              instructions_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return armmotorhelp.Proto2.internal_static_armmotorhelp_EmergencyStopAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return armmotorhelp.Proto2.internal_static_armmotorhelp_EmergencyStopAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              armmotorhelp.Proto2.EmergencyStopAck.class, armmotorhelp.Proto2.EmergencyStopAck.Builder.class);
    }

    public static final int MOTORS_STOPPED_FIELD_NUMBER = 1;
    private boolean motorsStopped_;
    /**
     * <code>bool motors_stopped = 1;</code>
     */
    public boolean getMotorsStopped() {
      return motorsStopped_;
    }

    public static final int INSTRUCTIONS_FIELD_NUMBER = 2;
    private volatile java.lang.Object instructions_;
    /**
     * <code>string instructions = 2;</code>
     */
    public java.lang.String getInstructions() {
      java.lang.Object ref = instructions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instructions_ = s;
        return s;
      }
    }
    /**
     * <code>string instructions = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInstructionsBytes() {
      java.lang.Object ref = instructions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instructions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (motorsStopped_ != false) {
        output.writeBool(1, motorsStopped_);
      }
      if (!getInstructionsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, instructions_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (motorsStopped_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, motorsStopped_);
      }
      if (!getInstructionsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, instructions_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof armmotorhelp.Proto2.EmergencyStopAck)) {
        return super.equals(obj);
      }
      armmotorhelp.Proto2.EmergencyStopAck other = (armmotorhelp.Proto2.EmergencyStopAck) obj;

      boolean result = true;
      result = result && (getMotorsStopped()
          == other.getMotorsStopped());
      result = result && getInstructions()
          .equals(other.getInstructions());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOTORS_STOPPED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMotorsStopped());
      hash = (37 * hash) + INSTRUCTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getInstructions().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static armmotorhelp.Proto2.EmergencyStopAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static armmotorhelp.Proto2.EmergencyStopAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(armmotorhelp.Proto2.EmergencyStopAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code armmotorhelp.EmergencyStopAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:armmotorhelp.EmergencyStopAck)
        armmotorhelp.Proto2.EmergencyStopAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_EmergencyStopAck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_EmergencyStopAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                armmotorhelp.Proto2.EmergencyStopAck.class, armmotorhelp.Proto2.EmergencyStopAck.Builder.class);
      }

      // Construct using armmotorhelp.Proto2.EmergencyStopAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        motorsStopped_ = false;

        instructions_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return armmotorhelp.Proto2.internal_static_armmotorhelp_EmergencyStopAck_descriptor;
      }

      @java.lang.Override
      public armmotorhelp.Proto2.EmergencyStopAck getDefaultInstanceForType() {
        return armmotorhelp.Proto2.EmergencyStopAck.getDefaultInstance();
      }

      @java.lang.Override
      public armmotorhelp.Proto2.EmergencyStopAck build() {
        armmotorhelp.Proto2.EmergencyStopAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public armmotorhelp.Proto2.EmergencyStopAck buildPartial() {
        armmotorhelp.Proto2.EmergencyStopAck result = new armmotorhelp.Proto2.EmergencyStopAck(this);
        result.motorsStopped_ = motorsStopped_;
        result.instructions_ = instructions_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof armmotorhelp.Proto2.EmergencyStopAck) {
          return mergeFrom((armmotorhelp.Proto2.EmergencyStopAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(armmotorhelp.Proto2.EmergencyStopAck other) {
        if (other == armmotorhelp.Proto2.EmergencyStopAck.getDefaultInstance()) return this;
        if (other.getMotorsStopped() != false) {
          setMotorsStopped(other.getMotorsStopped());
        }
        if (!other.getInstructions().isEmpty()) {
          instructions_ = other.instructions_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        armmotorhelp.Proto2.EmergencyStopAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (armmotorhelp.Proto2.EmergencyStopAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean motorsStopped_ ;
      /**
       * <code>bool motors_stopped = 1;</code>
       */
      public boolean getMotorsStopped() {
        return motorsStopped_;
      }
      /**
       * <code>bool motors_stopped = 1;</code>
       */
      public Builder setMotorsStopped(boolean value) {
        
        motorsStopped_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool motors_stopped = 1;</code>
       */
      public Builder clearMotorsStopped() {
        
        motorsStopped_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object instructions_ = "";
      /**
       * <code>string instructions = 2;</code>
       */
      public java.lang.String getInstructions() {
        java.lang.Object ref = instructions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instructions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instructions = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInstructionsBytes() {
        java.lang.Object ref = instructions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instructions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instructions = 2;</code>
       */
      public Builder setInstructions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instructions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string instructions = 2;</code>
       */
      public Builder clearInstructions() {
        
        instructions_ = getDefaultInstance().getInstructions();
        onChanged();
        return this;
      }
      /**
       * <code>string instructions = 2;</code>
       */
      public Builder setInstructionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        instructions_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:armmotorhelp.EmergencyStopAck)
    }

    // @@protoc_insertion_point(class_scope:armmotorhelp.EmergencyStopAck)
    private static final armmotorhelp.Proto2.EmergencyStopAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new armmotorhelp.Proto2.EmergencyStopAck();
    }

    public static armmotorhelp.Proto2.EmergencyStopAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmergencyStopAck>
        PARSER = new com.google.protobuf.AbstractParser<EmergencyStopAck>() {
      @java.lang.Override
      public EmergencyStopAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmergencyStopAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmergencyStopAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmergencyStopAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public armmotorhelp.Proto2.EmergencyStopAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armmotorhelp_ArmState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armmotorhelp_ArmState_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armmotorhelp_ArmSessionSummary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armmotorhelp_ArmSessionSummary_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armmotorhelp_EmergencyStopRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armmotorhelp_EmergencyStopRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armmotorhelp_EmergencyStopAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armmotorhelp_EmergencyStopAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014proto2.proto\022\014armmotorhelp\"1\n\010ArmState" +
      "\022\021\n\tworker_id\030\001 \001(\t\022\022\n\nmotor_load\030\002 \001(\002\"" +
      "B\n\021ArmSessionSummary\022\027\n\017session_summary\030" +
      "\001 \001(\t\022\024\n\014total_events\030\002 \001(\005\";\n\024Emergency" +
      "StopRequest\022\021\n\tworker_id\030\001 \001(\t\022\020\n\010locati" +
      "on\030\003 \001(\t\"@\n\020EmergencyStopAck\022\026\n\016motors_s" +
      "topped\030\001 \001(\010\022\024\n\014instructions\030\002 \001(\t2\267\001\n\023A" +
      "rmMotorHelpService\022K\n\016StreamArmState\022\026.a" +
      "rmmotorhelp.ArmState\032\037.armmotorhelp.ArmS" +
      "essionSummary(\001\022S\n\rEmergencyStop\022\".armmo" +
      "torhelp.EmergencyStopRequest\032\036.armmotorh" +
      "elp.EmergencyStopAckb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_armmotorhelp_ArmState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_armmotorhelp_ArmState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armmotorhelp_ArmState_descriptor,
        new java.lang.String[] { "WorkerId", "MotorLoad", });
    internal_static_armmotorhelp_ArmSessionSummary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_armmotorhelp_ArmSessionSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armmotorhelp_ArmSessionSummary_descriptor,
        new java.lang.String[] { "SessionSummary", "TotalEvents", });
    internal_static_armmotorhelp_EmergencyStopRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_armmotorhelp_EmergencyStopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armmotorhelp_EmergencyStopRequest_descriptor,
        new java.lang.String[] { "WorkerId", "Location", });
    internal_static_armmotorhelp_EmergencyStopAck_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_armmotorhelp_EmergencyStopAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armmotorhelp_EmergencyStopAck_descriptor,
        new java.lang.String[] { "MotorsStopped", "Instructions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
