// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package epilepsybracelet;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BiometricDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:epilepsybracelet.BiometricData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string worker_id = 1;</code>
     */
    java.lang.String getWorkerId();
    /**
     * <code>string worker_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getWorkerIdBytes();

    /**
     * <code>float heart_rate = 2;</code>
     */
    float getHeartRate();
  }
  /**
   * Protobuf type {@code epilepsybracelet.BiometricData}
   */
  public  static final class BiometricData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:epilepsybracelet.BiometricData)
      BiometricDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BiometricData.newBuilder() to construct.
    private BiometricData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BiometricData() {
      workerId_ = "";
      heartRate_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BiometricData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              workerId_ = s;
              break;
            }
            case 21: {

              heartRate_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return epilepsybracelet.Proto.internal_static_epilepsybracelet_BiometricData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return epilepsybracelet.Proto.internal_static_epilepsybracelet_BiometricData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              epilepsybracelet.Proto.BiometricData.class, epilepsybracelet.Proto.BiometricData.Builder.class);
    }

    public static final int WORKER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object workerId_;
    /**
     * <code>string worker_id = 1;</code>
     */
    public java.lang.String getWorkerId() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workerId_ = s;
        return s;
      }
    }
    /**
     * <code>string worker_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkerIdBytes() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEART_RATE_FIELD_NUMBER = 2;
    private float heartRate_;
    /**
     * <code>float heart_rate = 2;</code>
     */
    public float getHeartRate() {
      return heartRate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWorkerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workerId_);
      }
      if (heartRate_ != 0F) {
        output.writeFloat(2, heartRate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWorkerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workerId_);
      }
      if (heartRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, heartRate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof epilepsybracelet.Proto.BiometricData)) {
        return super.equals(obj);
      }
      epilepsybracelet.Proto.BiometricData other = (epilepsybracelet.Proto.BiometricData) obj;

      boolean result = true;
      result = result && getWorkerId()
          .equals(other.getWorkerId());
      result = result && (
          java.lang.Float.floatToIntBits(getHeartRate())
          == java.lang.Float.floatToIntBits(
              other.getHeartRate()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORKER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerId().hashCode();
      hash = (37 * hash) + HEART_RATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeartRate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static epilepsybracelet.Proto.BiometricData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.BiometricData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.BiometricData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.BiometricData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.BiometricData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.BiometricData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.BiometricData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.BiometricData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static epilepsybracelet.Proto.BiometricData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.BiometricData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static epilepsybracelet.Proto.BiometricData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.BiometricData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(epilepsybracelet.Proto.BiometricData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code epilepsybracelet.BiometricData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:epilepsybracelet.BiometricData)
        epilepsybracelet.Proto.BiometricDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_BiometricData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_BiometricData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                epilepsybracelet.Proto.BiometricData.class, epilepsybracelet.Proto.BiometricData.Builder.class);
      }

      // Construct using epilepsybracelet.Proto.BiometricData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        workerId_ = "";

        heartRate_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_BiometricData_descriptor;
      }

      @java.lang.Override
      public epilepsybracelet.Proto.BiometricData getDefaultInstanceForType() {
        return epilepsybracelet.Proto.BiometricData.getDefaultInstance();
      }

      @java.lang.Override
      public epilepsybracelet.Proto.BiometricData build() {
        epilepsybracelet.Proto.BiometricData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public epilepsybracelet.Proto.BiometricData buildPartial() {
        epilepsybracelet.Proto.BiometricData result = new epilepsybracelet.Proto.BiometricData(this);
        result.workerId_ = workerId_;
        result.heartRate_ = heartRate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof epilepsybracelet.Proto.BiometricData) {
          return mergeFrom((epilepsybracelet.Proto.BiometricData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(epilepsybracelet.Proto.BiometricData other) {
        if (other == epilepsybracelet.Proto.BiometricData.getDefaultInstance()) return this;
        if (!other.getWorkerId().isEmpty()) {
          workerId_ = other.workerId_;
          onChanged();
        }
        if (other.getHeartRate() != 0F) {
          setHeartRate(other.getHeartRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        epilepsybracelet.Proto.BiometricData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (epilepsybracelet.Proto.BiometricData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object workerId_ = "";
      /**
       * <code>string worker_id = 1;</code>
       */
      public java.lang.String getWorkerId() {
        java.lang.Object ref = workerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWorkerIdBytes() {
        java.lang.Object ref = workerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder setWorkerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder clearWorkerId() {
        
        workerId_ = getDefaultInstance().getWorkerId();
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder setWorkerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workerId_ = value;
        onChanged();
        return this;
      }

      private float heartRate_ ;
      /**
       * <code>float heart_rate = 2;</code>
       */
      public float getHeartRate() {
        return heartRate_;
      }
      /**
       * <code>float heart_rate = 2;</code>
       */
      public Builder setHeartRate(float value) {
        
        heartRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float heart_rate = 2;</code>
       */
      public Builder clearHeartRate() {
        
        heartRate_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:epilepsybracelet.BiometricData)
    }

    // @@protoc_insertion_point(class_scope:epilepsybracelet.BiometricData)
    private static final epilepsybracelet.Proto.BiometricData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new epilepsybracelet.Proto.BiometricData();
    }

    public static epilepsybracelet.Proto.BiometricData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BiometricData>
        PARSER = new com.google.protobuf.AbstractParser<BiometricData>() {
      @java.lang.Override
      public BiometricData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BiometricData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BiometricData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BiometricData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public epilepsybracelet.Proto.BiometricData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SeizureResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:epilepsybracelet.SeizureResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool trigger_stimulation = 1;</code>
     */
    boolean getTriggerStimulation();

    /**
     * <code>string alert_level = 2;</code>
     */
    java.lang.String getAlertLevel();
    /**
     * <code>string alert_level = 2;</code>
     */
    com.google.protobuf.ByteString
        getAlertLevelBytes();
  }
  /**
   * Protobuf type {@code epilepsybracelet.SeizureResponse}
   */
  public  static final class SeizureResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:epilepsybracelet.SeizureResponse)
      SeizureResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SeizureResponse.newBuilder() to construct.
    private SeizureResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SeizureResponse() {
      triggerStimulation_ = false;
      alertLevel_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SeizureResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              triggerStimulation_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              alertLevel_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return epilepsybracelet.Proto.internal_static_epilepsybracelet_SeizureResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return epilepsybracelet.Proto.internal_static_epilepsybracelet_SeizureResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              epilepsybracelet.Proto.SeizureResponse.class, epilepsybracelet.Proto.SeizureResponse.Builder.class);
    }

    public static final int TRIGGER_STIMULATION_FIELD_NUMBER = 1;
    private boolean triggerStimulation_;
    /**
     * <code>bool trigger_stimulation = 1;</code>
     */
    public boolean getTriggerStimulation() {
      return triggerStimulation_;
    }

    public static final int ALERT_LEVEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object alertLevel_;
    /**
     * <code>string alert_level = 2;</code>
     */
    public java.lang.String getAlertLevel() {
      java.lang.Object ref = alertLevel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertLevel_ = s;
        return s;
      }
    }
    /**
     * <code>string alert_level = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAlertLevelBytes() {
      java.lang.Object ref = alertLevel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (triggerStimulation_ != false) {
        output.writeBool(1, triggerStimulation_);
      }
      if (!getAlertLevelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, alertLevel_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (triggerStimulation_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, triggerStimulation_);
      }
      if (!getAlertLevelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, alertLevel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof epilepsybracelet.Proto.SeizureResponse)) {
        return super.equals(obj);
      }
      epilepsybracelet.Proto.SeizureResponse other = (epilepsybracelet.Proto.SeizureResponse) obj;

      boolean result = true;
      result = result && (getTriggerStimulation()
          == other.getTriggerStimulation());
      result = result && getAlertLevel()
          .equals(other.getAlertLevel());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRIGGER_STIMULATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTriggerStimulation());
      hash = (37 * hash) + ALERT_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getAlertLevel().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static epilepsybracelet.Proto.SeizureResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.SeizureResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(epilepsybracelet.Proto.SeizureResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code epilepsybracelet.SeizureResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:epilepsybracelet.SeizureResponse)
        epilepsybracelet.Proto.SeizureResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_SeizureResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_SeizureResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                epilepsybracelet.Proto.SeizureResponse.class, epilepsybracelet.Proto.SeizureResponse.Builder.class);
      }

      // Construct using epilepsybracelet.Proto.SeizureResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        triggerStimulation_ = false;

        alertLevel_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_SeizureResponse_descriptor;
      }

      @java.lang.Override
      public epilepsybracelet.Proto.SeizureResponse getDefaultInstanceForType() {
        return epilepsybracelet.Proto.SeizureResponse.getDefaultInstance();
      }

      @java.lang.Override
      public epilepsybracelet.Proto.SeizureResponse build() {
        epilepsybracelet.Proto.SeizureResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public epilepsybracelet.Proto.SeizureResponse buildPartial() {
        epilepsybracelet.Proto.SeizureResponse result = new epilepsybracelet.Proto.SeizureResponse(this);
        result.triggerStimulation_ = triggerStimulation_;
        result.alertLevel_ = alertLevel_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof epilepsybracelet.Proto.SeizureResponse) {
          return mergeFrom((epilepsybracelet.Proto.SeizureResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(epilepsybracelet.Proto.SeizureResponse other) {
        if (other == epilepsybracelet.Proto.SeizureResponse.getDefaultInstance()) return this;
        if (other.getTriggerStimulation() != false) {
          setTriggerStimulation(other.getTriggerStimulation());
        }
        if (!other.getAlertLevel().isEmpty()) {
          alertLevel_ = other.alertLevel_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        epilepsybracelet.Proto.SeizureResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (epilepsybracelet.Proto.SeizureResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean triggerStimulation_ ;
      /**
       * <code>bool trigger_stimulation = 1;</code>
       */
      public boolean getTriggerStimulation() {
        return triggerStimulation_;
      }
      /**
       * <code>bool trigger_stimulation = 1;</code>
       */
      public Builder setTriggerStimulation(boolean value) {
        
        triggerStimulation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool trigger_stimulation = 1;</code>
       */
      public Builder clearTriggerStimulation() {
        
        triggerStimulation_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object alertLevel_ = "";
      /**
       * <code>string alert_level = 2;</code>
       */
      public java.lang.String getAlertLevel() {
        java.lang.Object ref = alertLevel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          alertLevel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string alert_level = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAlertLevelBytes() {
        java.lang.Object ref = alertLevel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alertLevel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string alert_level = 2;</code>
       */
      public Builder setAlertLevel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        alertLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string alert_level = 2;</code>
       */
      public Builder clearAlertLevel() {
        
        alertLevel_ = getDefaultInstance().getAlertLevel();
        onChanged();
        return this;
      }
      /**
       * <code>string alert_level = 2;</code>
       */
      public Builder setAlertLevelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        alertLevel_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:epilepsybracelet.SeizureResponse)
    }

    // @@protoc_insertion_point(class_scope:epilepsybracelet.SeizureResponse)
    private static final epilepsybracelet.Proto.SeizureResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new epilepsybracelet.Proto.SeizureResponse();
    }

    public static epilepsybracelet.Proto.SeizureResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SeizureResponse>
        PARSER = new com.google.protobuf.AbstractParser<SeizureResponse>() {
      @java.lang.Override
      public SeizureResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SeizureResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SeizureResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SeizureResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public epilepsybracelet.Proto.SeizureResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmergencyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:epilepsybracelet.EmergencyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string worker_id = 1;</code>
     */
    java.lang.String getWorkerId();
    /**
     * <code>string worker_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getWorkerIdBytes();

    /**
     * <code>string location = 2;</code>
     */
    java.lang.String getLocation();
    /**
     * <code>string location = 2;</code>
     */
    com.google.protobuf.ByteString
        getLocationBytes();
  }
  /**
   * Protobuf type {@code epilepsybracelet.EmergencyRequest}
   */
  public  static final class EmergencyRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:epilepsybracelet.EmergencyRequest)
      EmergencyRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmergencyRequest.newBuilder() to construct.
    private EmergencyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmergencyRequest() {
      workerId_ = "";
      location_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmergencyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              workerId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              location_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return epilepsybracelet.Proto.internal_static_epilepsybracelet_EmergencyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return epilepsybracelet.Proto.internal_static_epilepsybracelet_EmergencyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              epilepsybracelet.Proto.EmergencyRequest.class, epilepsybracelet.Proto.EmergencyRequest.Builder.class);
    }

    public static final int WORKER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object workerId_;
    /**
     * <code>string worker_id = 1;</code>
     */
    public java.lang.String getWorkerId() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workerId_ = s;
        return s;
      }
    }
    /**
     * <code>string worker_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkerIdBytes() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 2;
    private volatile java.lang.Object location_;
    /**
     * <code>string location = 2;</code>
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <code>string location = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWorkerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workerId_);
      }
      if (!getLocationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, location_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWorkerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workerId_);
      }
      if (!getLocationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, location_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof epilepsybracelet.Proto.EmergencyRequest)) {
        return super.equals(obj);
      }
      epilepsybracelet.Proto.EmergencyRequest other = (epilepsybracelet.Proto.EmergencyRequest) obj;

      boolean result = true;
      result = result && getWorkerId()
          .equals(other.getWorkerId());
      result = result && getLocation()
          .equals(other.getLocation());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORKER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerId().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static epilepsybracelet.Proto.EmergencyRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.EmergencyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(epilepsybracelet.Proto.EmergencyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code epilepsybracelet.EmergencyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:epilepsybracelet.EmergencyRequest)
        epilepsybracelet.Proto.EmergencyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_EmergencyRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_EmergencyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                epilepsybracelet.Proto.EmergencyRequest.class, epilepsybracelet.Proto.EmergencyRequest.Builder.class);
      }

      // Construct using epilepsybracelet.Proto.EmergencyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        workerId_ = "";

        location_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_EmergencyRequest_descriptor;
      }

      @java.lang.Override
      public epilepsybracelet.Proto.EmergencyRequest getDefaultInstanceForType() {
        return epilepsybracelet.Proto.EmergencyRequest.getDefaultInstance();
      }

      @java.lang.Override
      public epilepsybracelet.Proto.EmergencyRequest build() {
        epilepsybracelet.Proto.EmergencyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public epilepsybracelet.Proto.EmergencyRequest buildPartial() {
        epilepsybracelet.Proto.EmergencyRequest result = new epilepsybracelet.Proto.EmergencyRequest(this);
        result.workerId_ = workerId_;
        result.location_ = location_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof epilepsybracelet.Proto.EmergencyRequest) {
          return mergeFrom((epilepsybracelet.Proto.EmergencyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(epilepsybracelet.Proto.EmergencyRequest other) {
        if (other == epilepsybracelet.Proto.EmergencyRequest.getDefaultInstance()) return this;
        if (!other.getWorkerId().isEmpty()) {
          workerId_ = other.workerId_;
          onChanged();
        }
        if (!other.getLocation().isEmpty()) {
          location_ = other.location_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        epilepsybracelet.Proto.EmergencyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (epilepsybracelet.Proto.EmergencyRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object workerId_ = "";
      /**
       * <code>string worker_id = 1;</code>
       */
      public java.lang.String getWorkerId() {
        java.lang.Object ref = workerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWorkerIdBytes() {
        java.lang.Object ref = workerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder setWorkerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder clearWorkerId() {
        
        workerId_ = getDefaultInstance().getWorkerId();
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder setWorkerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workerId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <code>string location = 2;</code>
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string location = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string location = 2;</code>
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string location = 2;</code>
       */
      public Builder clearLocation() {
        
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      /**
       * <code>string location = 2;</code>
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        location_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:epilepsybracelet.EmergencyRequest)
    }

    // @@protoc_insertion_point(class_scope:epilepsybracelet.EmergencyRequest)
    private static final epilepsybracelet.Proto.EmergencyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new epilepsybracelet.Proto.EmergencyRequest();
    }

    public static epilepsybracelet.Proto.EmergencyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmergencyRequest>
        PARSER = new com.google.protobuf.AbstractParser<EmergencyRequest>() {
      @java.lang.Override
      public EmergencyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmergencyRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmergencyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmergencyRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public epilepsybracelet.Proto.EmergencyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmergencyAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:epilepsybracelet.EmergencyAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool received = 1;</code>
     */
    boolean getReceived();

    /**
     * <code>string instructions = 2;</code>
     */
    java.lang.String getInstructions();
    /**
     * <code>string instructions = 2;</code>
     */
    com.google.protobuf.ByteString
        getInstructionsBytes();
  }
  /**
   * Protobuf type {@code epilepsybracelet.EmergencyAck}
   */
  public  static final class EmergencyAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:epilepsybracelet.EmergencyAck)
      EmergencyAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmergencyAck.newBuilder() to construct.
    private EmergencyAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmergencyAck() {
      received_ = false;
      instructions_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmergencyAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              received_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              instructions_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return epilepsybracelet.Proto.internal_static_epilepsybracelet_EmergencyAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return epilepsybracelet.Proto.internal_static_epilepsybracelet_EmergencyAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              epilepsybracelet.Proto.EmergencyAck.class, epilepsybracelet.Proto.EmergencyAck.Builder.class);
    }

    public static final int RECEIVED_FIELD_NUMBER = 1;
    private boolean received_;
    /**
     * <code>bool received = 1;</code>
     */
    public boolean getReceived() {
      return received_;
    }

    public static final int INSTRUCTIONS_FIELD_NUMBER = 2;
    private volatile java.lang.Object instructions_;
    /**
     * <code>string instructions = 2;</code>
     */
    public java.lang.String getInstructions() {
      java.lang.Object ref = instructions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instructions_ = s;
        return s;
      }
    }
    /**
     * <code>string instructions = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInstructionsBytes() {
      java.lang.Object ref = instructions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instructions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (received_ != false) {
        output.writeBool(1, received_);
      }
      if (!getInstructionsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, instructions_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (received_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, received_);
      }
      if (!getInstructionsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, instructions_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof epilepsybracelet.Proto.EmergencyAck)) {
        return super.equals(obj);
      }
      epilepsybracelet.Proto.EmergencyAck other = (epilepsybracelet.Proto.EmergencyAck) obj;

      boolean result = true;
      result = result && (getReceived()
          == other.getReceived());
      result = result && getInstructions()
          .equals(other.getInstructions());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RECEIVED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getReceived());
      hash = (37 * hash) + INSTRUCTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getInstructions().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static epilepsybracelet.Proto.EmergencyAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static epilepsybracelet.Proto.EmergencyAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(epilepsybracelet.Proto.EmergencyAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code epilepsybracelet.EmergencyAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:epilepsybracelet.EmergencyAck)
        epilepsybracelet.Proto.EmergencyAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_EmergencyAck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_EmergencyAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                epilepsybracelet.Proto.EmergencyAck.class, epilepsybracelet.Proto.EmergencyAck.Builder.class);
      }

      // Construct using epilepsybracelet.Proto.EmergencyAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        received_ = false;

        instructions_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return epilepsybracelet.Proto.internal_static_epilepsybracelet_EmergencyAck_descriptor;
      }

      @java.lang.Override
      public epilepsybracelet.Proto.EmergencyAck getDefaultInstanceForType() {
        return epilepsybracelet.Proto.EmergencyAck.getDefaultInstance();
      }

      @java.lang.Override
      public epilepsybracelet.Proto.EmergencyAck build() {
        epilepsybracelet.Proto.EmergencyAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public epilepsybracelet.Proto.EmergencyAck buildPartial() {
        epilepsybracelet.Proto.EmergencyAck result = new epilepsybracelet.Proto.EmergencyAck(this);
        result.received_ = received_;
        result.instructions_ = instructions_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof epilepsybracelet.Proto.EmergencyAck) {
          return mergeFrom((epilepsybracelet.Proto.EmergencyAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(epilepsybracelet.Proto.EmergencyAck other) {
        if (other == epilepsybracelet.Proto.EmergencyAck.getDefaultInstance()) return this;
        if (other.getReceived() != false) {
          setReceived(other.getReceived());
        }
        if (!other.getInstructions().isEmpty()) {
          instructions_ = other.instructions_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        epilepsybracelet.Proto.EmergencyAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (epilepsybracelet.Proto.EmergencyAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean received_ ;
      /**
       * <code>bool received = 1;</code>
       */
      public boolean getReceived() {
        return received_;
      }
      /**
       * <code>bool received = 1;</code>
       */
      public Builder setReceived(boolean value) {
        
        received_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool received = 1;</code>
       */
      public Builder clearReceived() {
        
        received_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object instructions_ = "";
      /**
       * <code>string instructions = 2;</code>
       */
      public java.lang.String getInstructions() {
        java.lang.Object ref = instructions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instructions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instructions = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInstructionsBytes() {
        java.lang.Object ref = instructions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instructions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instructions = 2;</code>
       */
      public Builder setInstructions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instructions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string instructions = 2;</code>
       */
      public Builder clearInstructions() {
        
        instructions_ = getDefaultInstance().getInstructions();
        onChanged();
        return this;
      }
      /**
       * <code>string instructions = 2;</code>
       */
      public Builder setInstructionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        instructions_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:epilepsybracelet.EmergencyAck)
    }

    // @@protoc_insertion_point(class_scope:epilepsybracelet.EmergencyAck)
    private static final epilepsybracelet.Proto.EmergencyAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new epilepsybracelet.Proto.EmergencyAck();
    }

    public static epilepsybracelet.Proto.EmergencyAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmergencyAck>
        PARSER = new com.google.protobuf.AbstractParser<EmergencyAck>() {
      @java.lang.Override
      public EmergencyAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmergencyAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmergencyAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmergencyAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public epilepsybracelet.Proto.EmergencyAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_epilepsybracelet_BiometricData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_epilepsybracelet_BiometricData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_epilepsybracelet_SeizureResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_epilepsybracelet_SeizureResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_epilepsybracelet_EmergencyRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_epilepsybracelet_EmergencyRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_epilepsybracelet_EmergencyAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_epilepsybracelet_EmergencyAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013proto.proto\022\020epilepsybracelet\"6\n\rBiome" +
      "tricData\022\021\n\tworker_id\030\001 \001(\t\022\022\n\nheart_rat" +
      "e\030\002 \001(\002\"C\n\017SeizureResponse\022\033\n\023trigger_st" +
      "imulation\030\001 \001(\010\022\023\n\013alert_level\030\002 \001(\t\"7\n\020" +
      "EmergencyRequest\022\021\n\tworker_id\030\001 \001(\t\022\020\n\010l" +
      "ocation\030\002 \001(\t\"6\n\014EmergencyAck\022\020\n\010receive" +
      "d\030\001 \001(\010\022\024\n\014instructions\030\002 \001(\t2\314\001\n\027Epilep" +
      "syBraceletService\022[\n\021MonitorBiometrics\022\037" +
      ".epilepsybracelet.BiometricData\032!.epilep" +
      "sybracelet.SeizureResponse(\0010\001\022T\n\016Emerge" +
      "ncyAlert\022\".epilepsybracelet.EmergencyReq" +
      "uest\032\036.epilepsybracelet.EmergencyAckb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_epilepsybracelet_BiometricData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_epilepsybracelet_BiometricData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_epilepsybracelet_BiometricData_descriptor,
        new java.lang.String[] { "WorkerId", "HeartRate", });
    internal_static_epilepsybracelet_SeizureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_epilepsybracelet_SeizureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_epilepsybracelet_SeizureResponse_descriptor,
        new java.lang.String[] { "TriggerStimulation", "AlertLevel", });
    internal_static_epilepsybracelet_EmergencyRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_epilepsybracelet_EmergencyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_epilepsybracelet_EmergencyRequest_descriptor,
        new java.lang.String[] { "WorkerId", "Location", });
    internal_static_epilepsybracelet_EmergencyAck_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_epilepsybracelet_EmergencyAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_epilepsybracelet_EmergencyAck_descriptor,
        new java.lang.String[] { "Received", "Instructions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
