// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto1.proto

package vibrationbeltguide;

public final class Proto1 {
  private Proto1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DestinationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vibrationbeltguide.DestinationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string worker_id = 1;</code>
     */
    java.lang.String getWorkerId();
    /**
     * <code>string worker_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getWorkerIdBytes();

    /**
     * <code>string destinationName = 2;</code>
     */
    java.lang.String getDestinationName();
    /**
     * <code>string destinationName = 2;</code>
     */
    com.google.protobuf.ByteString
        getDestinationNameBytes();
  }
  /**
   * Protobuf type {@code vibrationbeltguide.DestinationRequest}
   */
  public  static final class DestinationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:vibrationbeltguide.DestinationRequest)
      DestinationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DestinationRequest.newBuilder() to construct.
    private DestinationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DestinationRequest() {
      workerId_ = "";
      destinationName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DestinationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              workerId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              destinationName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_DestinationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_DestinationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vibrationbeltguide.Proto1.DestinationRequest.class, vibrationbeltguide.Proto1.DestinationRequest.Builder.class);
    }

    public static final int WORKER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object workerId_;
    /**
     * <code>string worker_id = 1;</code>
     */
    public java.lang.String getWorkerId() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workerId_ = s;
        return s;
      }
    }
    /**
     * <code>string worker_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkerIdBytes() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTINATIONNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object destinationName_;
    /**
     * <code>string destinationName = 2;</code>
     */
    public java.lang.String getDestinationName() {
      java.lang.Object ref = destinationName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationName_ = s;
        return s;
      }
    }
    /**
     * <code>string destinationName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationNameBytes() {
      java.lang.Object ref = destinationName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWorkerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workerId_);
      }
      if (!getDestinationNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destinationName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWorkerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workerId_);
      }
      if (!getDestinationNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, destinationName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vibrationbeltguide.Proto1.DestinationRequest)) {
        return super.equals(obj);
      }
      vibrationbeltguide.Proto1.DestinationRequest other = (vibrationbeltguide.Proto1.DestinationRequest) obj;

      boolean result = true;
      result = result && getWorkerId()
          .equals(other.getWorkerId());
      result = result && getDestinationName()
          .equals(other.getDestinationName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORKER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerId().hashCode();
      hash = (37 * hash) + DESTINATIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vibrationbeltguide.Proto1.DestinationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static vibrationbeltguide.Proto1.DestinationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vibrationbeltguide.Proto1.DestinationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vibrationbeltguide.DestinationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vibrationbeltguide.DestinationRequest)
        vibrationbeltguide.Proto1.DestinationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_DestinationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_DestinationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vibrationbeltguide.Proto1.DestinationRequest.class, vibrationbeltguide.Proto1.DestinationRequest.Builder.class);
      }

      // Construct using vibrationbeltguide.Proto1.DestinationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        workerId_ = "";

        destinationName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_DestinationRequest_descriptor;
      }

      @java.lang.Override
      public vibrationbeltguide.Proto1.DestinationRequest getDefaultInstanceForType() {
        return vibrationbeltguide.Proto1.DestinationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public vibrationbeltguide.Proto1.DestinationRequest build() {
        vibrationbeltguide.Proto1.DestinationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public vibrationbeltguide.Proto1.DestinationRequest buildPartial() {
        vibrationbeltguide.Proto1.DestinationRequest result = new vibrationbeltguide.Proto1.DestinationRequest(this);
        result.workerId_ = workerId_;
        result.destinationName_ = destinationName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vibrationbeltguide.Proto1.DestinationRequest) {
          return mergeFrom((vibrationbeltguide.Proto1.DestinationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vibrationbeltguide.Proto1.DestinationRequest other) {
        if (other == vibrationbeltguide.Proto1.DestinationRequest.getDefaultInstance()) return this;
        if (!other.getWorkerId().isEmpty()) {
          workerId_ = other.workerId_;
          onChanged();
        }
        if (!other.getDestinationName().isEmpty()) {
          destinationName_ = other.destinationName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vibrationbeltguide.Proto1.DestinationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vibrationbeltguide.Proto1.DestinationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object workerId_ = "";
      /**
       * <code>string worker_id = 1;</code>
       */
      public java.lang.String getWorkerId() {
        java.lang.Object ref = workerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWorkerIdBytes() {
        java.lang.Object ref = workerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder setWorkerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder clearWorkerId() {
        
        workerId_ = getDefaultInstance().getWorkerId();
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 1;</code>
       */
      public Builder setWorkerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workerId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object destinationName_ = "";
      /**
       * <code>string destinationName = 2;</code>
       */
      public java.lang.String getDestinationName() {
        java.lang.Object ref = destinationName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destinationName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string destinationName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationNameBytes() {
        java.lang.Object ref = destinationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destinationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destinationName = 2;</code>
       */
      public Builder setDestinationName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destinationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string destinationName = 2;</code>
       */
      public Builder clearDestinationName() {
        
        destinationName_ = getDefaultInstance().getDestinationName();
        onChanged();
        return this;
      }
      /**
       * <code>string destinationName = 2;</code>
       */
      public Builder setDestinationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destinationName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:vibrationbeltguide.DestinationRequest)
    }

    // @@protoc_insertion_point(class_scope:vibrationbeltguide.DestinationRequest)
    private static final vibrationbeltguide.Proto1.DestinationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vibrationbeltguide.Proto1.DestinationRequest();
    }

    public static vibrationbeltguide.Proto1.DestinationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DestinationRequest>
        PARSER = new com.google.protobuf.AbstractParser<DestinationRequest>() {
      @java.lang.Override
      public DestinationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DestinationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DestinationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DestinationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public vibrationbeltguide.Proto1.DestinationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DestinationAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vibrationbeltguide.DestinationAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool accepted = 1;</code>
     */
    boolean getAccepted();

    /**
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>float estimatedDistance = 3;</code>
     */
    float getEstimatedDistance();
  }
  /**
   * Protobuf type {@code vibrationbeltguide.DestinationAck}
   */
  public  static final class DestinationAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:vibrationbeltguide.DestinationAck)
      DestinationAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DestinationAck.newBuilder() to construct.
    private DestinationAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DestinationAck() {
      accepted_ = false;
      message_ = "";
      estimatedDistance_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DestinationAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              accepted_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 29: {

              estimatedDistance_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_DestinationAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_DestinationAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vibrationbeltguide.Proto1.DestinationAck.class, vibrationbeltguide.Proto1.DestinationAck.Builder.class);
    }

    public static final int ACCEPTED_FIELD_NUMBER = 1;
    private boolean accepted_;
    /**
     * <code>bool accepted = 1;</code>
     */
    public boolean getAccepted() {
      return accepted_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ESTIMATEDDISTANCE_FIELD_NUMBER = 3;
    private float estimatedDistance_;
    /**
     * <code>float estimatedDistance = 3;</code>
     */
    public float getEstimatedDistance() {
      return estimatedDistance_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (accepted_ != false) {
        output.writeBool(1, accepted_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (estimatedDistance_ != 0F) {
        output.writeFloat(3, estimatedDistance_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (accepted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, accepted_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (estimatedDistance_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, estimatedDistance_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vibrationbeltguide.Proto1.DestinationAck)) {
        return super.equals(obj);
      }
      vibrationbeltguide.Proto1.DestinationAck other = (vibrationbeltguide.Proto1.DestinationAck) obj;

      boolean result = true;
      result = result && (getAccepted()
          == other.getAccepted());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && (
          java.lang.Float.floatToIntBits(getEstimatedDistance())
          == java.lang.Float.floatToIntBits(
              other.getEstimatedDistance()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCEPTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAccepted());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + ESTIMATEDDISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getEstimatedDistance());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vibrationbeltguide.Proto1.DestinationAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static vibrationbeltguide.Proto1.DestinationAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vibrationbeltguide.Proto1.DestinationAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vibrationbeltguide.DestinationAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vibrationbeltguide.DestinationAck)
        vibrationbeltguide.Proto1.DestinationAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_DestinationAck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_DestinationAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vibrationbeltguide.Proto1.DestinationAck.class, vibrationbeltguide.Proto1.DestinationAck.Builder.class);
      }

      // Construct using vibrationbeltguide.Proto1.DestinationAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        accepted_ = false;

        message_ = "";

        estimatedDistance_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_DestinationAck_descriptor;
      }

      @java.lang.Override
      public vibrationbeltguide.Proto1.DestinationAck getDefaultInstanceForType() {
        return vibrationbeltguide.Proto1.DestinationAck.getDefaultInstance();
      }

      @java.lang.Override
      public vibrationbeltguide.Proto1.DestinationAck build() {
        vibrationbeltguide.Proto1.DestinationAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public vibrationbeltguide.Proto1.DestinationAck buildPartial() {
        vibrationbeltguide.Proto1.DestinationAck result = new vibrationbeltguide.Proto1.DestinationAck(this);
        result.accepted_ = accepted_;
        result.message_ = message_;
        result.estimatedDistance_ = estimatedDistance_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vibrationbeltguide.Proto1.DestinationAck) {
          return mergeFrom((vibrationbeltguide.Proto1.DestinationAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vibrationbeltguide.Proto1.DestinationAck other) {
        if (other == vibrationbeltguide.Proto1.DestinationAck.getDefaultInstance()) return this;
        if (other.getAccepted() != false) {
          setAccepted(other.getAccepted());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.getEstimatedDistance() != 0F) {
          setEstimatedDistance(other.getEstimatedDistance());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vibrationbeltguide.Proto1.DestinationAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vibrationbeltguide.Proto1.DestinationAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean accepted_ ;
      /**
       * <code>bool accepted = 1;</code>
       */
      public boolean getAccepted() {
        return accepted_;
      }
      /**
       * <code>bool accepted = 1;</code>
       */
      public Builder setAccepted(boolean value) {
        
        accepted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool accepted = 1;</code>
       */
      public Builder clearAccepted() {
        
        accepted_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private float estimatedDistance_ ;
      /**
       * <code>float estimatedDistance = 3;</code>
       */
      public float getEstimatedDistance() {
        return estimatedDistance_;
      }
      /**
       * <code>float estimatedDistance = 3;</code>
       */
      public Builder setEstimatedDistance(float value) {
        
        estimatedDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float estimatedDistance = 3;</code>
       */
      public Builder clearEstimatedDistance() {
        
        estimatedDistance_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:vibrationbeltguide.DestinationAck)
    }

    // @@protoc_insertion_point(class_scope:vibrationbeltguide.DestinationAck)
    private static final vibrationbeltguide.Proto1.DestinationAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vibrationbeltguide.Proto1.DestinationAck();
    }

    public static vibrationbeltguide.Proto1.DestinationAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DestinationAck>
        PARSER = new com.google.protobuf.AbstractParser<DestinationAck>() {
      @java.lang.Override
      public DestinationAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DestinationAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DestinationAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DestinationAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public vibrationbeltguide.Proto1.DestinationAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VibrationCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vibrationbeltguide.VibrationCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string direction = 1;</code>
     */
    java.lang.String getDirection();
    /**
     * <code>string direction = 1;</code>
     */
    com.google.protobuf.ByteString
        getDirectionBytes();

    /**
     * <code>int32 intensity = 2;</code>
     */
    int getIntensity();

    /**
     * <code>bool obstacleDetected = 3;</code>
     */
    boolean getObstacleDetected();
  }
  /**
   * Protobuf type {@code vibrationbeltguide.VibrationCommand}
   */
  public  static final class VibrationCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:vibrationbeltguide.VibrationCommand)
      VibrationCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VibrationCommand.newBuilder() to construct.
    private VibrationCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VibrationCommand() {
      direction_ = "";
      intensity_ = 0;
      obstacleDetected_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VibrationCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              direction_ = s;
              break;
            }
            case 16: {

              intensity_ = input.readInt32();
              break;
            }
            case 24: {

              obstacleDetected_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_VibrationCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_VibrationCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vibrationbeltguide.Proto1.VibrationCommand.class, vibrationbeltguide.Proto1.VibrationCommand.Builder.class);
    }

    public static final int DIRECTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object direction_;
    /**
     * <code>string direction = 1;</code>
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      }
    }
    /**
     * <code>string direction = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTENSITY_FIELD_NUMBER = 2;
    private int intensity_;
    /**
     * <code>int32 intensity = 2;</code>
     */
    public int getIntensity() {
      return intensity_;
    }

    public static final int OBSTACLEDETECTED_FIELD_NUMBER = 3;
    private boolean obstacleDetected_;
    /**
     * <code>bool obstacleDetected = 3;</code>
     */
    public boolean getObstacleDetected() {
      return obstacleDetected_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDirectionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, direction_);
      }
      if (intensity_ != 0) {
        output.writeInt32(2, intensity_);
      }
      if (obstacleDetected_ != false) {
        output.writeBool(3, obstacleDetected_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDirectionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, direction_);
      }
      if (intensity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, intensity_);
      }
      if (obstacleDetected_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, obstacleDetected_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vibrationbeltguide.Proto1.VibrationCommand)) {
        return super.equals(obj);
      }
      vibrationbeltguide.Proto1.VibrationCommand other = (vibrationbeltguide.Proto1.VibrationCommand) obj;

      boolean result = true;
      result = result && getDirection()
          .equals(other.getDirection());
      result = result && (getIntensity()
          == other.getIntensity());
      result = result && (getObstacleDetected()
          == other.getObstacleDetected());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
      hash = (37 * hash) + INTENSITY_FIELD_NUMBER;
      hash = (53 * hash) + getIntensity();
      hash = (37 * hash) + OBSTACLEDETECTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getObstacleDetected());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vibrationbeltguide.Proto1.VibrationCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static vibrationbeltguide.Proto1.VibrationCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vibrationbeltguide.Proto1.VibrationCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vibrationbeltguide.VibrationCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vibrationbeltguide.VibrationCommand)
        vibrationbeltguide.Proto1.VibrationCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_VibrationCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_VibrationCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vibrationbeltguide.Proto1.VibrationCommand.class, vibrationbeltguide.Proto1.VibrationCommand.Builder.class);
      }

      // Construct using vibrationbeltguide.Proto1.VibrationCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        direction_ = "";

        intensity_ = 0;

        obstacleDetected_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vibrationbeltguide.Proto1.internal_static_vibrationbeltguide_VibrationCommand_descriptor;
      }

      @java.lang.Override
      public vibrationbeltguide.Proto1.VibrationCommand getDefaultInstanceForType() {
        return vibrationbeltguide.Proto1.VibrationCommand.getDefaultInstance();
      }

      @java.lang.Override
      public vibrationbeltguide.Proto1.VibrationCommand build() {
        vibrationbeltguide.Proto1.VibrationCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public vibrationbeltguide.Proto1.VibrationCommand buildPartial() {
        vibrationbeltguide.Proto1.VibrationCommand result = new vibrationbeltguide.Proto1.VibrationCommand(this);
        result.direction_ = direction_;
        result.intensity_ = intensity_;
        result.obstacleDetected_ = obstacleDetected_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vibrationbeltguide.Proto1.VibrationCommand) {
          return mergeFrom((vibrationbeltguide.Proto1.VibrationCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vibrationbeltguide.Proto1.VibrationCommand other) {
        if (other == vibrationbeltguide.Proto1.VibrationCommand.getDefaultInstance()) return this;
        if (!other.getDirection().isEmpty()) {
          direction_ = other.direction_;
          onChanged();
        }
        if (other.getIntensity() != 0) {
          setIntensity(other.getIntensity());
        }
        if (other.getObstacleDetected() != false) {
          setObstacleDetected(other.getObstacleDetected());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vibrationbeltguide.Proto1.VibrationCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vibrationbeltguide.Proto1.VibrationCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object direction_ = "";
      /**
       * <code>string direction = 1;</code>
       */
      public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string direction = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string direction = 1;</code>
       */
      public Builder setDirection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 1;</code>
       */
      public Builder clearDirection() {
        
        direction_ = getDefaultInstance().getDirection();
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 1;</code>
       */
      public Builder setDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        direction_ = value;
        onChanged();
        return this;
      }

      private int intensity_ ;
      /**
       * <code>int32 intensity = 2;</code>
       */
      public int getIntensity() {
        return intensity_;
      }
      /**
       * <code>int32 intensity = 2;</code>
       */
      public Builder setIntensity(int value) {
        
        intensity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intensity = 2;</code>
       */
      public Builder clearIntensity() {
        
        intensity_ = 0;
        onChanged();
        return this;
      }

      private boolean obstacleDetected_ ;
      /**
       * <code>bool obstacleDetected = 3;</code>
       */
      public boolean getObstacleDetected() {
        return obstacleDetected_;
      }
      /**
       * <code>bool obstacleDetected = 3;</code>
       */
      public Builder setObstacleDetected(boolean value) {
        
        obstacleDetected_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool obstacleDetected = 3;</code>
       */
      public Builder clearObstacleDetected() {
        
        obstacleDetected_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:vibrationbeltguide.VibrationCommand)
    }

    // @@protoc_insertion_point(class_scope:vibrationbeltguide.VibrationCommand)
    private static final vibrationbeltguide.Proto1.VibrationCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vibrationbeltguide.Proto1.VibrationCommand();
    }

    public static vibrationbeltguide.Proto1.VibrationCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VibrationCommand>
        PARSER = new com.google.protobuf.AbstractParser<VibrationCommand>() {
      @java.lang.Override
      public VibrationCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VibrationCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VibrationCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VibrationCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public vibrationbeltguide.Proto1.VibrationCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vibrationbeltguide_DestinationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vibrationbeltguide_DestinationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vibrationbeltguide_DestinationAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vibrationbeltguide_DestinationAck_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vibrationbeltguide_VibrationCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vibrationbeltguide_VibrationCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014proto1.proto\022\022vibrationbeltguide\"@\n\022De" +
      "stinationRequest\022\021\n\tworker_id\030\001 \001(\t\022\027\n\017d" +
      "estinationName\030\002 \001(\t\"N\n\016DestinationAck\022\020" +
      "\n\010accepted\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\031\n\021est" +
      "imatedDistance\030\003 \001(\002\"R\n\020VibrationCommand" +
      "\022\021\n\tdirection\030\001 \001(\t\022\021\n\tintensity\030\002 \001(\005\022\030" +
      "\n\020obstacleDetected\030\003 \001(\0102\341\001\n\031VibrationBe" +
      "ltGuideService\022`\n\022RequestDestination\022&.v" +
      "ibrationbeltguide.DestinationRequest\032\".v" +
      "ibrationbeltguide.DestinationAck\022b\n\020Stre" +
      "amNavigation\022&.vibrationbeltguide.Destin" +
      "ationRequest\032$.vibrationbeltguide.Vibrat" +
      "ionCommand0\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vibrationbeltguide_DestinationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vibrationbeltguide_DestinationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vibrationbeltguide_DestinationRequest_descriptor,
        new java.lang.String[] { "WorkerId", "DestinationName", });
    internal_static_vibrationbeltguide_DestinationAck_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vibrationbeltguide_DestinationAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vibrationbeltguide_DestinationAck_descriptor,
        new java.lang.String[] { "Accepted", "Message", "EstimatedDistance", });
    internal_static_vibrationbeltguide_VibrationCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_vibrationbeltguide_VibrationCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vibrationbeltguide_VibrationCommand_descriptor,
        new java.lang.String[] { "Direction", "Intensity", "ObstacleDetected", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
